//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WVAPIDbEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IBCashActivity
    {
        public string AccountName { get; set; }
        public System.DateTime SettleDate { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime LastUpdated { get; set; }
    }
}
